### ISSUE TITLE
npm i -g saucectl gives access denied error

### ISSUE THREAD

**Issue by jawadqur** [saucelabs/node-saucectl#14]
## Expected Behavior
Expected behavior is that saucectl is installed globally, without throwing exception

## Actual Behavior
Throws exception on MacOs Big Sur 11.3.1 and Ubuntu 18.04

```
sudo npm i -g saucectl
/usr/bin/saucectl -> /usr/lib/node_modules/saucectl/index.js

> saucectl@0.99.1 install /usr/lib/node_modules/saucectl
> node install.js

Fetching saucectl binary
Installation failed: Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/saucectl/bin'
Check that you have access to https://github.com/saucelabs/saucectl/releases or format of the SAUCECTL_INSTALL_BINARY environment variable is correct


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! saucectl@0.99.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the saucectl@0.99.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2022-05-22T23_29_25_288Z-debug.log

```

## Steps to Reproduce the Problem

  1. Run the `npm i -g saucectl` command.

## Specifications

  - Version: latest
  - Platform: MacOs, Ubuntu
  - Subsystem:Big Sierra, 18.04

**Comment by alexplischke** [comment]
This is not an issue with the install script, but rather the permission settings in your environment.
Please check out the following resources for a solution:
- https://stackoverflow.com/questions/38323880/error-eacces-permission-denied
- https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally
